spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer
  profiles:
    active: production

# ACTUATOR INFO
management:
  endpoints:
    web:
      exposure:
        include: {'info','health','refresh','metrics','mappings'}

info:
  app:
    name: "Customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}